[package]
name = "hooser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspaces]

[dependencies]
hooser-derive = { path = "hooser-derive" }
toml = "0.8.19"
